
package com.qas.ondemand_2011_03;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QASOnDemandIntermediary", targetNamespace = "http://www.qas.com/OnDemand-2011-03", wsdlLocation = "https://ws2.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?WSDL")
public class QASOnDemandIntermediary
    extends Service
{

    private final static URL QASONDEMANDINTERMEDIARY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.qas.ondemand_2011_03.QASOnDemandIntermediary.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.qas.ondemand_2011_03.QASOnDemandIntermediary.class.getResource(".");
            url = new URL(baseUrl, "https://ws2.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://ws2.ondemand.qas.com/ProOnDemand/V3/ProOnDemandService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QASONDEMANDINTERMEDIARY_WSDL_LOCATION = url;
    }
    
    public QASOnDemandIntermediary(URL wsdlLocation) {
    	super(wsdlLocation, new QName("http://www.qas.com/OnDemand-2011-03", "QASOnDemandIntermediary"));
    }

    public QASOnDemandIntermediary(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QASOnDemandIntermediary() {
        super(QASONDEMANDINTERMEDIARY_WSDL_LOCATION, new QName("http://www.qas.com/OnDemand-2011-03", "QASOnDemandIntermediary"));
    }

    /**
     * 
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType() {
        return super.getPort(new QName("http://www.qas.com/OnDemand-2011-03", "QAPortType"), QAPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QAPortType
     */
    @WebEndpoint(name = "QAPortType")
    public QAPortType getQAPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.qas.com/OnDemand-2011-03", "QAPortType"), QAPortType.class);
    }

}
